var bodModalBlock=function(){"use strict";var $=jQuery.noConflict();const focusableElements='button, [href], input, select, textarea, [tabindex]:not([tabindex="-1"])';var bodModalCount=0;var bodModalActive=false;var bodModals=[];var initElements=function(){bodModalCount=0;bodModalActive=false;bodModals=[];$('.wp-block-bod-modal-block').each(function(){bodModals.push(new BodModal(this));});};var checkForCookie=function(cookieName){let name=cookieName+"=";let decodedCookie=decodeURIComponent(document.cookie);let ca=decodedCookie.split(';');for(let i=0;i<ca.length;i++){let c=ca[i];while(c.charAt(0)==' '){c=c.substring(1);}
if(c.indexOf(name)==0){return c.substring(name.length,c.length);}}
return"";}
var BodModal=function(container){this.$container=$(container);this.$trigger=this.$container.find('.bod-block-popup-trigger');this.$overlay=this.$container.find('.bod-block-popup-overlay');bodModalCount++;this.$container.find('.bod-block-popup-wrap').attr('aria-labelledby','bodModalAriaTitle'+bodModalCount);this.$container.find('.bod-modal-title').attr('id','bodModalAriaTitle'+bodModalCount);this.$container.find('.bod-block-popup-wrap').attr('aria-describedby','bodModalAriaContent'+bodModalCount);this.$container.find('.bod-modal-content').attr('id','bodModalAriaContent'+bodModalCount);this.show=this.show.bind(this);this.afterShow=this.afterShow.bind(this);this.hide=this.hide.bind(this);this.keyPress=this.keyPress.bind(this);this.timer=null;if(this.$trigger.hasClass('type_selector')){var triggerSelector=this.$trigger.attr('data-selector');if(triggerSelector){$('.'+triggerSelector).css('cursor','pointer').on('click',this.show);}}else if(this.$trigger.hasClass('type_load')){var loadOnce=this.$trigger.attr('data-once');var triggerTimer=true;if(loadOnce){if(loadOnce==='yes'){let modalId=this.$trigger.attr('data-id');if(!modalId)modalId="";let modalOnce=checkForCookie("bodModalOnce"+modalId);if(modalOnce)triggerTimer=false;}}
var loadurl=this.$trigger.attr('data-urltrig');if(loadurl){if(window.location.href.indexOf(loadurl)===-1)triggerTimer=false;}
if(triggerTimer){var loadDelay=this.$trigger.attr('data-delay');isNaN(parseInt(loadDelay))?loadDelay=1000:loadDelay=parseInt(loadDelay);if(loadOnce){let modalId=this.$trigger.attr('data-id');if(!modalId)modalId="";let noShowDays=this.$trigger.attr('data-days');isNaN(parseInt(noShowDays))?noShowDays=30:noShowDays=parseInt(noShowDays);this.timer=setTimeout(this.show,loadDelay,loadOnce,modalId,noShowDays);}else{this.timer=setTimeout(this.show,loadDelay);}}}else{this.$trigger.on('click',this.show);}
var disableOverlayClose=this.$overlay.attr('data-disabled-overlay-close');if(!disableOverlayClose){this.$overlay.on('click',this.hide);}else{if(disableOverlayClose==='false'){this.$overlay.on('click',this.hide);}}
var disableEscapeClose=this.$overlay.attr('data-disabled-escape-close');if(!disableEscapeClose){this.disableEscapeClose=false;}else{if(disableEscapeClose==='true'){this.disableEscapeClose=true;}else{this.disableEscapeClose=false;}}
this.$modalWrap=this.$container.find('.bod-block-popup-wrap');this.$modal=this.$container.find('.bod-block-popup');this.$modalcloser=this.$container.find('.bod-block-popup-closer').on('click',this.hide);this.$titlecloser=this.$container.find('.bod-block-title-closer').on('click',this.hide);this.$btncloser=this.$container.find('.bod-block-close-btn .bod-btn').on('click',this.hide);this.$modalToModal=this.$container.find('.bod-modal-to-modal').on('click',this.hide);this.$escCloser=$(document).on('keydown',this.keyPress);this.modalWrap=container.querySelector('.bod-block-popup-wrap');this.focusableContent=this.modalWrap.querySelectorAll(focusableElements);if(this.focusableContent){this.firstFocusableElement=this.focusableContent[0];this.lastFocusableElement=this.focusableContent[this.focusableContent.length-1];}
this.modalOpen=false;}
BodModal.prototype={show:function(loadOnce,modalId,noShowDays){$(document).trigger("bod-modal-before-open",this.$modalWrap);if(this.$trigger.hasClass('type_load')&&bodModalActive===true){return;}
bodModalActive=true;if(loadOnce){if(loadOnce!=='no'){const d=new Date();d.setTime(d.getTime()+(noShowDays*24*60*60*1000));let expires="expires="+d.toUTCString();if(modalId){var cookie="bodModalOnce"+modalId;}else{var cookie="bodModalOnce";}
document.cookie=cookie+"="+loadOnce+";"+expires+";path=/";}}
clearTimeout(this.timer);this.$overlay.appendTo(document.body).show();this.$modalWrap.appendTo(document.body).show();this.timer=setTimeout(this.afterShow,25);},afterShow:function(){clearTimeout(this.timer);if(this.transition=this.$modal.attr('data-transition')){if(this.transition=='left'){this.$modal.addClass('slide-right');}else if(this.transition=='right'){this.$modal.addClass('slide-left');}else if(this.transition=='bottom'){this.$modal.addClass('slide-up');}else if(this.transition=='top'){this.$modal.addClass('slide-down');}else{this.$modal.addClass('fade');};}else{this.$modal.addClass('fade');};this.$overlay.addClass('active');this.$modalWrap.addClass('active');this.$modalWrap.attr('aria-modal','true');this.modalOpen=true;this.triggerElement=document.activeElement;if(this.firstFocusableElement){this.firstFocusableElement.focus({preventScroll:true});}else{document.activeElement.blur();}
$(document).trigger("bod-modal-after-open",this.$modalWrap);},hide:function(){if($(document).trigger("bod-modal-before-close",this.$modalWrap).data('cancel')){return;};this.$overlay.removeClass('active');this.$modalWrap.removeClass('active');this.$overlay.appendTo(this.$container).hide();this.$modalWrap.appendTo(this.$container).hide();this.$modalWrap.attr('aria-modal','false');bodModalActive=false;this.modalOpen=false;$(document).trigger("bod-modal-after-close",this.$modalWrap);if(this.triggerElement)this.triggerElement.focus({preventScroll:true});},keyPress:function(e){if(e.keyCode===27&&!this.disableEscapeClose){this.hide();}
if(this.modalOpen){let isTabPressed=e.key==='Tab'||e.keyCode===9;if(!isTabPressed){return;}
if(this.firstFocusableElement){if(e.shiftKey){if(document.activeElement===this.firstFocusableElement){this.lastFocusableElement.focus();e.preventDefault();}}else{if(document.activeElement===this.lastFocusableElement){this.firstFocusableElement.focus();e.preventDefault();}}}else{e.preventDefault();}}},}
return{initModal:initElements}};var bodModal=bodModalBlock();jQuery(document).ready(function($){bodModal.initModal();});