var menuToggle=document.querySelector('.nav-toggle');var menu=document.querySelector('.nav-bottom-mobile-dropdown');var expandButtons=document.querySelectorAll('.expand-button');var navLinks=document.querySelectorAll('.nav li a');var searchButton=document.querySelector('.search-button');var searchContainer=document.querySelector('.nav-bottom-search');searchButton.onclick=function(){searchContainer.classList.toggle('search-off');};expandButtons.forEach((el)=>el.addEventListener('click',(event)=>{toggleClass(el.parentElement,'block-expanded');toggleImageExpand(el.firstChild);togglePanelExpand(el);}));toggleImageExpand=function(child){if(child.src.includes(templateDir+'/img/expand_close-icon.svg')){child.src=templateDir+'/img/expand_open-icon.svg';}else{child.src=templateDir+'/img/expand_close-icon.svg';}};togglePanelExpand=function(el){var objParent=$(el).parents('.interior-blocks-item');console.log(objParent);objParent.find('.blocks-expanded-info').animate({height:"toggle"},250);}
menuToggle.onclick=function(){closeHeaderPanels();toggleClass(menu,'menu-off');updateMobileMenuPosition();};function toggleClass(element,className){if(element.classList.contains(className)){element.classList.remove(className);}else{element.classList.add(className);}}
function addClass(element,className){element.classList.add(className);}
function removeClass(element,className){element.classList.remove(className);}
function updateMobileMenuPosition(){var mobileNavContent=document.querySelector('.nav-bottom-mobile .nav-bottom-content');var mobileDropdown=document.querySelector('.nav-bottom-mobile-dropdown');if(!mobileNavContent||!mobileDropdown){return;}
var menuTop=Math.max(0,Math.floor(mobileNavContent.getBoundingClientRect().bottom));mobileDropdown.style.setProperty('--mobile-menu-top',menuTop+'px');}
function closeMobileMenu(){if(menu){addClass(menu,'menu-off');updateMobileMenuPosition();}}
function closeHeaderLoginPanel(){$('.headerCloseButton').css('display','none');$('.headerLoginButton').css({opacity:'1',cursor:'pointer'});$('.login-form').css('display','none');}
function closeHeaderAccountPanel(){$('#myaccount').css('display','none');}
function closeHeaderPanels(){closeHeaderLoginPanel();closeHeaderAccountPanel();}
$('.mobileNavLinks li a').click(function(){var currentMobileNav=$(this).next();currentMobileNav.toggleClass('mobileSubmenuActive');if($(currentMobileNav).hasClass('mobileSubmenuActive')){$(this).toggleClass('mobileNavLinksActive');}else{$(this).removeClass('mobileNavLinksActive');}});$('.mobileNavLinks li a').click(function(e){if($(this).next().hasClass('mobileNavSubmenu')){e.preventDefault();}});$('.mobileNavLinks li').each(function(){if($(this).children('ul').length>0){$(this).children('a').append('<img src="'+templateDir+'/img/down-icon.svg" class="down-icon" alt="Expand List" style="margin-left: 0.5rem;">');}});$(function(){initLoginDrop();initStickyHeader();$('.headerLoginButton').on('click',function(){closeMobileMenu();closeHeaderAccountPanel();$('.headerLoginButton').click(false);$('.headerLoginButton').css('opacity','0');$('.headerLoginButton').css('cursor','default');$('.headerCloseButton').css('display','block');$('.login-form').css('display','block');});$('.headerCloseButton').on('click',function(){$('.headerCloseButton').click(false);closeHeaderLoginPanel();});$('#headerMyAccountButton').on('click',function(){var shouldOpenAccount=$('#myaccount').css('display')=='none';closeMobileMenu();closeHeaderLoginPanel();if(shouldOpenAccount){$('#myaccount').css('display','block');}else{$('#myaccount').css('display','none');};});$('#login_username, #login_password').on('keyup',function(event){if(event.key==='Enter'||event.keyCode===13){userLogin(false);}});});$(window).resize(function(){initLoginDrop();});function initLoginDrop(){var isDesktopNav=window.matchMedia('(min-width: 1200px)').matches;if(isDesktopNav){$('#loginNav').appendTo('#headerLoginDesktop');$('#myAccountNav').appendTo('#headerLoginDesktop');$('#loginNav').removeClass('mobile');}else{$('#loginNav').appendTo('#nav-bottom-mobile .nav-bottom-content');$('#myAccountNav').appendTo('#nav-bottom-mobile .nav-bottom-content');$('#loginNav').addClass('mobile');}
$('.headerLoginButton').css({opacity:'1',cursor:'pointer'});$('.headerCloseButton').css('display','none');$('.login-form').css('display','none');}
function initStickyHeader(){var body=document.body;var desktopTop=document.querySelector('.nav-top-desktop');var desktopBottom=document.querySelector('.nav-bottom-desktop');var mobileTop=document.querySelector('.nav-top-mobile');var mobileBottom=document.querySelector('.nav-bottom-mobile');var mobileBottomContent=mobileBottom?mobileBottom.querySelector('.nav-bottom-content'):null;function updateStickyHeader(){var isDesktop=window.innerWidth>1199;var shouldStick=false;var stickyOffset=0;if(isDesktop&&desktopTop&&desktopBottom){shouldStick=window.scrollY>desktopTop.offsetHeight;stickyOffset=desktopBottom.offsetHeight;}else if(!isDesktop&&mobileTop&&mobileBottom){shouldStick=window.scrollY>mobileTop.offsetHeight;stickyOffset=mobileBottomContent?mobileBottomContent.offsetHeight:mobileBottom.offsetHeight;}
if(desktopBottom){desktopBottom.classList.toggle('is-fixed',isDesktop&&shouldStick);}
if(mobileBottom){mobileBottom.classList.toggle('is-fixed',!isDesktop&&shouldStick);}
if(mobileTop){mobileTop.classList.toggle('is-hidden',!isDesktop&&shouldStick);}
if(!shouldStick){body.classList.remove('sticky-header-active');body.style.removeProperty('--sticky-header-offset');updateMobileMenuPosition();return;}
body.classList.add('sticky-header-active');body.style.setProperty('--sticky-header-offset',stickyOffset+'px');updateMobileMenuPosition();}
updateStickyHeader();window.addEventListener('scroll',updateStickyHeader,{passive:true});window.addEventListener('resize',updateStickyHeader);if(window.visualViewport){window.visualViewport.addEventListener('resize',updateMobileMenuPosition);}}
function closepop(strID){$('#'+strID).fadeOut();}
function openpop(strID){$('#'+strID).css("display","flex").hide().fadeIn();}
function isTouchDevice(){return window.matchMedia("(hover: none), (pointer: coarse)").matches;}
function userLogin(blnMobile){strUsername=$('#login_username').val();strPassword=$('#login_password').val();$('.headerLoginForm .loading').css('display','block');jQuery.ajax({url:'/wp-admin/admin-ajax.php',dataType:'json',xhrFields:{withCredentials:true},data:({action:'ajaxUserLogin',username:strUsername,password:strPassword}),success:function(objData,strStatus,jqXHR){console.log(objData);$('.headerLoginForm .loading').css('display','none');if(objData.result){document.cookie="AccessKey="+objData.user.AccessKey+"; expires=0; path=/; domain=stacksbowers.com";$('.accountdrop').css('display','block');$('.accountdrop').removeClass('hidden');$('#login-form').css('display','none');$('.loginNav').css('display','none');if(objData.redirect_to){window.location.href=objData.redirect_to;}
else if(document.body.classList.contains('reload-after-login')){location.reload();}}else{$('#login-form .banner.error').css('display','block');$('#login-form .banner.error').html(objData.errors[0]);}}});}
function userLogout(){var xhr=new XMLHttpRequest();var url='https://auctions.stacksbowers.com/logout';xhr.open("GET",url,true);xhr.withCredentials=true;xhr.onreadystatechange=function(){if(this.readyState===4&&this.status===200){var redirectUrl=new URL(window.location.href);redirectUrl.searchParams.set('action','LOGOUT');redirectUrl.hash='';window.location.href=redirectUrl.toString();}}
xhr.send();}
function updateWantlistSummary(){jQuery.ajax({url:'/wp-admin/admin-ajax.php',dataType:'json',xhrFields:{withCredentials:true},data:({action:'ajaxUpdateWantlistSummary'}),success:function(objData,strStatus,jqXHR){}});}
function newsletterSignup(strEmail,arrMoreFields){$('#listSignupLoading').fadeIn(250);jQuery.ajax({url:'/wp-admin/admin-ajax.php',dataType:'json',data:({action:'ajaxAddToMailingList',EMAIL:strEmail,FNAME:arrMoreFields.Fname,LNAME:arrMoreFields.Lname,ENEWSLETTE:arrMoreFields.Newsletter,BULLION:arrMoreFields.Bullion,US:arrMoreFields.USnum,WORLD:arrMoreFields.WORLDnum,CONSIGN:arrMoreFields.Selling}),success:function(objData,strStatus,jqXHR){if(objData.success==true){if($('#emailpreferences').length&&$('#email_address').length&&strEmail.toLowerCase()===$('#email_address').val().toLowerCase()){window.location.reload();return;}
$('#listpopup .signupform, #listpopup .button').css('display','none');$('#listpopup .thankyou').css('display','block');}else{$('#listpopup .submiterror').html('<strong>We are sorry, an unexpected error occurred!</strong><br /> '+objData.message);$('#listpopup .submiterror').css('display','block');};$('#listSignupLoading').fadeOut(250);}});}
function listSignup(){var blnError=false;var objOptions={chkNewsletter:'No',chkBullion:'No',chkUSnum:'No',chkWORLDnum:'No',chkSelling:'No'};var strEmail=$('#listSignupEmail').val();var strFname=$('#listSignupFname').val();var strLname=$('#listSignupLname').val();$.each(objOptions,function(key,value){if($('#'+key).is(":checked")==true){objOptions[key]='Yes';};});if(strEmail==''){blnError=true;$('#listSignupError_email').css('display','block');$('#listSignupEmail').addClass('error');}else{blnError=false;$('#listSignupError_email').css('display','none');$('#listSignupEmail').removeClass('error');};var arrAddInfo={Email:strEmail,Fname:strFname,Lname:strLname,Newsletter:objOptions.chkNewsletter,Bullion:objOptions.chkBullion,USnum:objOptions.chkUSnum,WORLDnum:objOptions.chkWORLDnum,Selling:objOptions.chkSelling};if(blnError==false){newsletterSignup(strEmail,arrAddInfo);};};var popupProductflag=false;function popupProduct(target){if(document.getElementsByClassName("popup_title show")[0]!=undefined)
document.getElementsByClassName("popup_title show")[0].classList.remove("show");target.children[1].classList.toggle("show");popupProductflag=true;}
function removePopup(){if(document.getElementsByClassName("popup_title show")[0]!=undefined&&popupProductflag==false)
document.getElementsByClassName("popup_title show")[0].classList.remove("show");popupProductflag=false;}