document.addEventListener("DOMContentLoaded",function(){let index=0;const carousel=document.getElementById("carousel");const arrowLeft=document.getElementById("arrowLeft");const arrowRight=document.getElementById("arrowRight");const dotsContainer=document.getElementById("dotsContainer");const MOBILE_BREAKPOINT=768;const MOBILE_ITEMS_TO_SHOW=1;const DESKTOP_ITEMS_TO_SHOW=4;const TOTAL_ITEMS_IN_CAROUSEL=12;const SWIPE_THRESHOLD=50;const DESKTOP_ROTATION_COUNT=4;const MOBILE_ROTATION_COUNT=1;function getItemsToShow(){return window.innerWidth<=MOBILE_BREAKPOINT?MOBILE_ITEMS_TO_SHOW:DESKTOP_ITEMS_TO_SHOW;}
function createDots(){dotsContainer.innerHTML="";const dotsCount=TOTAL_ITEMS_IN_CAROUSEL;for(let i=0;i<dotsCount;i++){let dot=document.createElement("span");dot.classList.add("dot");if(i===index)dot.classList.add("active");dot.addEventListener("click",()=>goToSlide(i));dotsContainer.appendChild(dot);}}
function updateDots(){document.querySelectorAll(".dot").forEach((dot,i)=>{dot.classList.toggle("active",i===index);});}
function updateArrowVisibility(){arrowLeft.style.display=index===0?"none":"block";arrowRight.style.display=index>=TOTAL_ITEMS_IN_CAROUSEL-getItemsToShow()?"none":"block";}
function moveSlide(step){index+=step;if(index<0)index=0;if(index>TOTAL_ITEMS_IN_CAROUSEL-getItemsToShow())index=TOTAL_ITEMS_IN_CAROUSEL-getItemsToShow();carousel.style.transform=`translateX(${-index * (100 / getItemsToShow())}%)`;updateDots();updateArrowVisibility();}
function goToSlide(slideIndex){index=slideIndex;carousel.style.transform=`translateX(${-index * (100 / getItemsToShow())}%)`;updateDots();updateArrowVisibility();}
function enableSwipe(){let startX=0;let endX=0;carousel.addEventListener("touchstart",(e)=>{startX=e.touches[0].clientX;});carousel.addEventListener("touchend",(e)=>{endX=e.changedTouches[0].clientX;const diff=startX-endX;if(diff>SWIPE_THRESHOLD){moveSlide(MOBILE_ROTATION_COUNT);}else if(diff<-SWIPE_THRESHOLD){moveSlide(-MOBILE_ROTATION_COUNT);}});}
createDots();updateDots();updateArrowVisibility();enableSwipe();if(window.innerWidth<=MOBILE_BREAKPOINT){arrowLeft.addEventListener("click",()=>moveSlide(-MOBILE_ROTATION_COUNT));arrowRight.addEventListener("click",()=>moveSlide(MOBILE_ROTATION_COUNT));}
else{arrowLeft.addEventListener("click",()=>moveSlide(-DESKTOP_ROTATION_COUNT));arrowRight.addEventListener("click",()=>moveSlide(DESKTOP_ROTATION_COUNT));}
window.addEventListener("resize",()=>{createDots();updateDots();updateArrowVisibility();});});